#! /bin/sh



pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V


bash ~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
picom --experimental-backends &
feh --bg-scale ~/.config/bspwm/wallpaper/back.png &
setxkbmap latam &
wmname LG3D &

bspc config border_width         0
bspc config window_gap           9
bspc config left_padding         8
bspc config right_padding        8
bspc config top_padding          55
bspc config bottom_padding       10

bspc config presel_feedback_color \#00121C
bspc config focused_border_color \#094558
bspc config normal_border_color \#00121C

bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a firefoxdeveloperedition desktop='^2' follow=on
bspc rule -a jetbrains-datagrip desktop='^4' follow=on
bspc rule -a Viewnior desktop='^5' 
bspc rule -a kitty desktop='^1'
bspc rule -a Code desktop='^1'
bspc rule -a Chromium desktop='^2'

#xprop WM_CLASS //reconocimiento de aplicaciones

#documents
bspc rule -a wps desktop='^4' follow=on
bspc rule -a et desktop='^4' follow=on
bspc rule -a pdf desktop='^4' follow=on
bspc rule -a wpp desktop='^4' follow=on

#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

